# Generated by Django 2.2.4 on 2019-09-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190903_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrelation',
            old_name='follower_id',
            new_name='follow_user',
        ),
        migrations.RenameField(
            model_name='followrelation',
            old_name='user_id',
            new_name='user',
        ),
    ]
