# Generated by Django 2.2.4 on 2019-09-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrelation',
            name='follow_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.User', to_field='pub_id'),
        ),
        migrations.AlterField(
            model_name='followrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='users.User', to_field='pub_id'),
        ),
    ]
