# Generated by Django 2.2.4 on 2019-10-16 23:16

from django.db import migrations, models
import users.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190903_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.CharField(choices=[('01-mexican.svg', '01-mexican'), ('02-man.svg', '02-man'), ('03-pirates.svg', '03-pirates'), ('04-girl.svg', '04-girl'), ('05-boy.svg', '05-boy'), ('06-chinese.svg', '06-chinese'), ('07-man.svg', '07-man'), ('08-police.svg', '08-police'), ('09-french.svg', '09-french'), ('10-girl.svg', '10-girl'), ('11-girl.svg', '11-girl'), ('12-arab.svg', '12-arab'), ('13-rock.svg', '13-rock'), ('14-boy.svg', '14-boy'), ('15-chinese.svg', '15-chinese'), ('16-girl.svg', '16-girl'), ('17-nun.svg', '17-nun'), ('18-baby.svg', '18-baby'), ('19-vietnam.svg', '19-vietnam'), ('20-clown.svg', '20-clown'), ('21-indian.svg', '21-indian'), ('22-portuguese.svg', '22-portuguese'), ('23-oldster.svg', '23-oldster'), ('24-girl.svg', '24-girl'), ('25-armenian.svg', '25-armenian'), ('26-japan.svg', '26-japan'), ('27-ninja.svg', '27-ninja'), ('28-soldier.svg', '28-soldier'), ('29-girl.svg', '29-girl'), ('30-viking.svg', '30-viking'), ('31-boy.svg', '31-boy'), ('32-arab.svg', '32-arab'), ('33-indian.svg', '33-indian'), ('34-oldster.svg', '34-oldster'), ('35-armenian.svg', '35-armenian'), ('36-user.svg', '36-user'), ('37-dj.svg', '37-dj'), ('38-girl.svg', '38-girl'), ('39-girl.svg', '39-girl'), ('40-safari.svg', '40-safari'), ('41-cowboy.svg', '41-cowboy'), ('42-boy.svg', '42-boy'), ('43-santa clause.svg', '43-santa clause'), ('44-native.svg', '44-native'), ('45-doctor.svg', '45-doctor'), ('46-russia.svg', '46-russia'), ('47-scientist.svg', '47-scientist'), ('48-girl.svg', '48-girl'), ('49-bellboy.svg', '49-bellboy'), ('50-king.svg', '50-king')], default=users.models.profile.get_random_icon, max_length=100),
        ),
    ]
