# Generated by Django 2.2.4 on 2019-10-16 23:18

from django.db import migrations, models
import users.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191017_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.CharField(choices=[('01-mexican.svg', 'mexican'), ('02-man.svg', 'man'), ('03-pirates.svg', 'pirates'), ('04-girl.svg', 'girl'), ('05-boy.svg', 'boy'), ('06-chinese.svg', 'chinese'), ('07-man.svg', 'man'), ('08-police.svg', 'police'), ('09-french.svg', 'french'), ('10-girl.svg', 'girl'), ('11-girl.svg', 'girl'), ('12-arab.svg', 'arab'), ('13-rock.svg', 'rock'), ('14-boy.svg', 'boy'), ('15-chinese.svg', 'chinese'), ('16-girl.svg', 'girl'), ('17-nun.svg', 'nun'), ('18-baby.svg', 'baby'), ('19-vietnam.svg', 'vietnam'), ('20-clown.svg', 'clown'), ('21-indian.svg', 'indian'), ('22-portuguese.svg', 'portuguese'), ('23-oldster.svg', 'oldster'), ('24-girl.svg', 'girl'), ('25-armenian.svg', 'armenian'), ('26-japan.svg', 'japan'), ('27-ninja.svg', 'ninja'), ('28-soldier.svg', 'soldier'), ('29-girl.svg', 'girl'), ('30-viking.svg', 'viking'), ('31-boy.svg', 'boy'), ('32-arab.svg', 'arab'), ('33-indian.svg', 'indian'), ('34-oldster.svg', 'oldster'), ('35-armenian.svg', 'armenian'), ('36-user.svg', 'user'), ('37-dj.svg', 'dj'), ('38-girl.svg', 'girl'), ('39-girl.svg', 'girl'), ('40-safari.svg', 'safari'), ('41-cowboy.svg', 'cowboy'), ('42-boy.svg', 'boy'), ('43-santa clause.svg', 'santa clause'), ('44-native.svg', 'native'), ('45-doctor.svg', 'doctor'), ('46-russia.svg', 'russia'), ('47-scientist.svg', 'scientist'), ('48-girl.svg', 'girl'), ('49-bellboy.svg', 'bellboy'), ('50-king.svg', 'king')], default=users.models.profile.get_random_icon, max_length=100),
        ),
    ]
