# Generated by Django 2.2.4 on 2019-10-14 18:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='学年(半角数字)')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1, unique=True, verbose_name='小学、中学、高校、大学(修士・博士）')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='教科名')),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publisher', models.CharField(blank=True, max_length=20, verbose_name='出版社')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='教科書名')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='TextbookUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='単元名')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Textbook')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='言葉')),
                ('mean', models.CharField(max_length=100, verbose_name='意味')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Subject')),
                ('textbook_unit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='study.TextbookUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='単元名')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='textbookunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Unit'),
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.School'),
        ),
    ]
