# Generated by Django 2.2.4 on 2019-10-17 18:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_auto_20191017_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.IntegerField(verbose_name='学年(半角数字)')),
            ],
            options={
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='出版社')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2, unique=True, verbose_name='小学、中学、高校、大学(修士・博士）')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='教科名')),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='教科書名')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Grade')),
                ('publisher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='study.Publisher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='TextbookChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='章')),
            ],
        ),
        migrations.CreateModel(
            name='TextbookUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='単元名')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Textbook')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='言葉')),
                ('mean', models.CharField(max_length=100, verbose_name='意味')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Subject')),
                ('textbook_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='study.TextbookChapter')),
                ('textbook_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='study.TextbookUnit')),
            ],
        ),
        migrations.CreateModel(
            name='WordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer', to='study.Word')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word', to='study.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='単元名')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Grade')),
                ('parent', models.ManyToManyField(blank=True, related_name='_unit_parent_+', to='study.Unit', verbose_name='親単元')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Subject')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('grade'), descending=True, nulls_last=True)],
            },
        ),
        migrations.AddField(
            model_name='textbookunit',
            name='unit',
            field=models.ManyToManyField(to='study.Unit'),
        ),
        migrations.AddField(
            model_name='textbookchapter',
            name='textbook_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.TextbookUnit'),
        ),
        migrations.AddField(
            model_name='textbookchapter',
            name='unit',
            field=models.ManyToManyField(blank=True, to='study.Unit'),
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.School'),
        ),
    ]
