# Generated by Django 2.2.4 on 2019-10-19 00:21

from django.db import migrations, models
import django.db.models.deletion
import study.base_session
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191017_0818'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', study.base_session.BaseSessionManager()),
            ],
        ),
        migrations.CreateModel(
            name='WordGet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('get_range', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordPractice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer', to='study.Word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='study.StudySession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', study.base_session.BaseSessionManager()),
            ],
        ),
        migrations.DeleteModel(
            name='WordHistory',
        ),
        migrations.AddField(
            model_name='wordpractice',
            name='sub_session',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='study.WordSession'),
        ),
        migrations.AddField(
            model_name='wordpractice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
        migrations.AddField(
            model_name='wordpractice',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word', to='study.Word'),
        ),
        migrations.AddField(
            model_name='wordget',
            name='sub_session',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='study.WordSession'),
        ),
        migrations.AddField(
            model_name='wordget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
    ]
