# Generated by Django 2.2.4 on 2019-10-20 21:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20191019_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='word',
            name='textbook_chapter',
        ),
        migrations.RemoveField(
            model_name='word',
            name='textbook_unit',
        ),
        migrations.CreateModel(
            name='TextbookWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('textbook_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='study.TextbookChapter')),
                ('textbook_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.TextbookUnit')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.Word')),
            ],
        ),
    ]
