# Generated by Django 2.2.4 on 2019-10-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20191015_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=1, verbose_name='学年(半角数字)'),
        ),
    ]
