# Generated by Django 2.2.4 on 2019-10-20 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20191021_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
        migrations.AlterField(
            model_name='wordget',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
        migrations.AlterField(
            model_name='wordpractice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
        migrations.AlterField(
            model_name='wordsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
    ]
