# Generated by Django 2.2.4 on 2019-10-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20191015_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_unit_parent_+', to='study.Unit', verbose_name='親単元'),
        ),
        migrations.AlterField(
            model_name='word',
            name='textbook_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='study.TextbookUnit'),
        ),
    ]
