# Generated by Django 2.2.4 on 2019-10-14 19:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20191015_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbookunit',
            name='unit',
        ),
        migrations.AddField(
            model_name='textbookunit',
            name='unit',
            field=models.ManyToManyField(to='study.Unit'),
        ),
        migrations.CreateModel(
            name='TextbookChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='章')),
                ('textbook_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.TextbookUnit')),
                ('unit', models.ManyToManyField(blank=True, to='study.Unit')),
            ],
        ),
    ]
