# Generated by Django 2.2.4 on 2019-10-14 21:39

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20191015_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['school', 'name']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('grade'), descending=True, nulls_last=True)]},
        ),
    ]
