# Generated by Django 2.2.4 on 2019-10-14 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20191015_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='textbook_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='study.TextbookChapter'),
        ),
    ]
