# Generated by Django 2.2.4 on 2019-10-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190903_0351'),
        ('study', '0007_word_textbook_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer', to='study.Word')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word', to='study.Word')),
            ],
        ),
    ]
